# Generated by Django 4.2.1 on 2023-06-28 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0007_alter_profile_height_alter_profile_weight'),
        ('macros_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrosplanner',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profile_.profile'),
        ),
    ]
