# Generated by Django 4.2.1 on 2023-06-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros_sheet', '0006_macrossheet_cho_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrossheet',
            name='ptn_level',
            field=models.CharField(default='is_normal_ptn', max_length=20),
        ),
    ]
