# Generated by Django 4.2.1 on 2023-12-24 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_options', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodoptions',
            old_name='name',
            new_name='food',
        ),
    ]
