# Generated by Django 4.2.1 on 2023-06-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0006_alter_profile_height_alter_profile_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
