# Generated by Django 4.0.4 on 2024-08-25 17:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecords',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('morning_meal', models.BooleanField(default=False)),
                ('afternoon_meal', models.BooleanField(default=False)),
                ('evening_meal', models.BooleanField(default=False)),
                ('bowel_movements', models.IntegerField(default=0)),
                ('hunger_times', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=10)),
                ('stress_times', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=10)),
                ('anxiety_times', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=10)),
                ('craving_times', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=10)),
                ('athlete', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.athlete')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
