# Generated by Django 5.0 on 2024-08-17 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('morning_meal', models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0)),
                ('afternoon_meal', models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0)),
                ('evening_meal', models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0)),
                ('bowel_movements', models.IntegerField(default=0)),
                ('hunger_times', models.JSONField(blank=True, default=list)),
                ('stress_times', models.JSONField(blank=True, default=list)),
                ('anxiety_times', models.JSONField(blank=True, default=list)),
                ('craving_times', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
