# Generated by Django 5.0 on 2024-08-17 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0002_alter_dailyrecords_afternoon_meal_and_more'),
        ('profile_', '0011_alter_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyrecords',
            name='user',
        ),
        migrations.AddField(
            model_name='dailyrecords',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profile_.profile'),
        ),
    ]
