# Generated by Django 5.0 on 2024-08-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_records', '0003_remove_dailyrecords_user_dailyrecords_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecords',
            name='anxiety_times',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dailyrecords',
            name='craving_times',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dailyrecords',
            name='hunger_times',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dailyrecords',
            name='stress_times',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=10),
        ),
    ]
