# Generated by Django 4.2.1 on 2023-12-24 22:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meal', '0002_rename_diet_meal_rename_diet_meal_diet'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_of_measurement', models.CharField(choices=[('g', 'g'), ('U', 'U'), ('ml', 'ml')], max_length=50)),
                ('meal', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='meal.meal')),
            ],
        ),
    ]
