# Generated by Django 5.0 on 2024-08-10 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_', '0011_alter_profile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacrosPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profile_.profile')),
            ],
        ),
    ]
