# Generated by Django 4.2.1 on 2023-06-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MacrosSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cho', models.FloatField(default=0)),
                ('ptn', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('kcal_level', models.CharField(max_length=20)),
            ],
        ),
    ]
