# Generated by Django 4.2.1 on 2023-06-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros_sheet', '0008_macrossheet_fat_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrossheet',
            name='cho_proportion',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='macrossheet',
            name='fat_proportion',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='macrossheet',
            name='ptn_proportion',
            field=models.FloatField(default=0),
        ),
    ]
