# Generated by Django 4.2.1 on 2023-06-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macros_sheet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macrossheet',
            name='kcal_level',
        ),
    ]
