# Generated by Django 4.2.1 on 2023-06-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros_sheet', '0005_macrossheet_kcal'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrossheet',
            name='cho_level',
            field=models.CharField(default='is_normal_cho', max_length=20),
        ),
    ]
