# Generated by Django 4.2.1 on 2023-12-24 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meal', '0002_rename_diet_meal_rename_diet_meal_diet'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealGeneralInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.FloatField(verbose_name='00:00:00')),
                ('type_of_meal', models.CharField(choices=[('Ordinary', 'Ordinary'), ('Free Meal', 'Free Meal'), ('Pre Workout', 'Pre Workout'), ('Post Workout', 'Post Workout')], max_length=50)),
                ('meal', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='meal.meal')),
            ],
        ),
    ]
