# Generated by Django 4.2.1 on 2023-12-24 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_rename_diet_meal_rename_diet_meal_diet'),
        ('meal_general_info', '0002_alter_mealgeneralinfo_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealgeneralinfo',
            name='meal',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='meal.meal'),
        ),
    ]
