# Generated by Django 4.2.1 on 2023-12-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_general_info', '0003_alter_mealgeneralinfo_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealgeneralinfo',
            name='type_of_meal',
            field=models.CharField(choices=[('Ordinary', 'Ordinary'), ('Free Meal', 'Free Meal'), ('Pre Workout', 'Pre Workout'), ('Post Workout', 'Post Workout')], default='Ordinary', max_length=50),
        ),
    ]
