# Generated by Django 4.2.1 on 2023-12-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros_sheet', '0011_alter_macrossheet_cho_alter_macrossheet_fat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrossheet',
            name='week',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
