# Generated by Django 4.0.4 on 2024-08-25 17:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('time', models.TimeField(default='00:00:00')),
                ('type_of_meal', models.CharField(choices=[('Ordinary', 'Ordinary'), ('Free Meal', 'Free Meal'), ('Pre Workout', 'Pre Workout'), ('Post Workout', 'Post Workout')], default='Ordinary', max_length=50)),
                ('diet', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='diet.diet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
