# Generated by Django 4.0.4 on 2024-08-19 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.TimeField(default='00:00:00')),
                ('type_of_meal', models.CharField(choices=[('Ordinary', 'Ordinary'), ('Free Meal', 'Free Meal'), ('Pre Workout', 'Pre Workout'), ('Post Workout', 'Post Workout')], default='Ordinary', max_length=50)),
                ('diet', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='diet.diet')),
            ],
        ),
    ]
