# Generated by Django 4.2.1 on 2023-06-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros_sheet', '0004_alter_macrossheet_kcal_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrossheet',
            name='kcal',
            field=models.FloatField(default=0),
        ),
    ]
