# Generated by Django 4.2.1 on 2023-12-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_general_info', '0002_alter_dietgeneralinfo_diet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietgeneralinfo',
            name='type_of_diet',
            field=models.CharField(choices=[('Maintenance', 'Maintenance'), ('Bulking', 'Bulking'), ('Cutting', 'Cutting')], default='Maintenance', max_length=50),
        ),
    ]
