# Generated by Django 4.2.1 on 2023-06-28 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macros_planner', '0002_macrosplanner_profile'),
        ('general_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='macros_planner',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='macros_planner.macrosplanner'),
        ),
    ]
