# Generated by Django 4.2.1 on 2023-12-24 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
        ('diet_general_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietgeneralinfo',
            name='diet',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='diet.diet'),
        ),
    ]
