# Generated by Django 4.2.1 on 2023-12-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_options', '0002_rename_name_foodoptions_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodoptions',
            name='unit_of_measurement',
            field=models.CharField(choices=[('g', 'g'), ('U', 'U'), ('ml', 'ml')], default='g', max_length=50),
        ),
    ]
