# Generated by Django 4.2.1 on 2023-06-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros_sheet', '0002_remove_macrossheet_kcal_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrossheet',
            name='kcal_level',
            field=models.FloatField(default=0),
        ),
    ]
