# Generated by Django 4.2.1 on 2023-12-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_general_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealgeneralinfo',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
