# Generated by Django 4.2.2 on 2023-06-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0004_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
