# Generated by Django 4.0.4 on 2024-08-25 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macros_planner', '0001_initial'),
        ('macros_sheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macrossheet',
            name='macros_planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macros_sheets', to='macros_planner.macrosplanner'),
        ),
    ]
