# Generated by Django 4.0.4 on 2024-08-19 00:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(blank=True, max_length=100)),
                ('observations', models.CharField(blank=True, max_length=300)),
                ('initial_date', models.DateField()),
                ('final_date', models.DateField()),
                ('weeks', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('type_of_diet', models.CharField(choices=[('Maintenance', 'Maintenance'), ('Bulking', 'Bulking'), ('Cutting', 'Cutting')], default='Maintenance', max_length=50)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.athlete')),
                ('nutritionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.nutritionist')),
            ],
        ),
    ]
