# Generated by Django 4.0.4 on 2024-08-25 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diet', '0001_initial'),
        ('macros_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='macros_planner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='macros_planner.macrosplanner'),
        ),
    ]
